language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: 91df18b8-1a7f-4c91-bef6-f8280332a40b
  app: wwcd-dfs
  on:
    repo: maxemileffort/wwcd-fullstack-capstone-react
