language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: D68GtOyJmqYcA1Ead19Uw8fzoVU79Jf+IUIUe3Qu7BKqPxSKws6+ZQ83T9pWxLiCSs3rq1En2agbyEjwvYt4lLd3NJnlhD/aspSWN3zPmyw5xHZIu5n8TZXaEn0ijVaGasXl+XJJIvplGJ3CuGup6tSSu5Xy5jIrSp1hjd21H0v5OsKirVA8yVTzvLB4TQKGDAzd2VoGhkkuRxeZWEIhtDuOWaYZsPIEVyp0CTqc11IxSIa6ZKGRQK/3zZwbkg7lcLNMR5orOg6qdVL8skGDfSg4fNkcFK7WlEh5KGB9p5OP8P8tgxMudk567duYECcBOQWbrHuhH77s0y/HVBsLrWZ8ewreVhCOqeCSobi5j0jIuW6zqfDUybSpfMpCi66lE/foZzE5JNZHvrUalnwE6Fb7z9jupQjMT+pCJe0M9+R0WkgEKvU5NYycrXohFHX34uUwIbVhCQqVXS5GURIinIUdYoGiVWB1TM0iUmFEZN3yWGwU87QCoVKcGEaVGBdHqqGuV6DxC9W/esjzgfIFBRgPEi9xWWNcEzX+anhGkxY3qzAmmVTxEG3QbIHILz4OXfzr4jp83BRXT6m9t9AE1PkAXHzzdfbi6q4nI5VG1vkde4PKZeolqbarHX39uC3SeUBZOBM2/d+r2hVlW6mC8abMJwxBkuL+aQzjUE5GFhg=
  app: wwcd-dfs
  on:
    repo: maxemileffort/wwcd-fullstack-capstone-react
